### ISSUE TITLE
feat: Create a logger that will log all the requests and errors

### ISSUE THREAD

**Issue by aayushchugh** [maya-manager/server#55]
### Project

Server

### Description

We need to implement a logger that will log all the requests and uncaught exceptions and errors

### Anything else?

How to implement global error logger:- https://blog.devops.dev/throw-like-a-pro-in-nestjs-6b4dca2b935c
> scroll down to step 4

**Comment by BitOfAByte** [comment]
I'll work on that

**Comment by aayushchugh** [comment]
Done by @BitOfAByte
